# latexmk settings for the book (read automatically when latexmk runs in this folder)
$pdf_mode = 5;                                        # XeLaTeX
$makeindex = 'makeindex -s tools/index.ist %O -o %D %S';   # index with letter headings
